image: node:20.12.2 # Use a Node.js image that includes npm

services:
  - docker:dind

# Define the stages of the pipeline
stages:
  - setup
  - install
  - build
  - deploy

# Setup Stage
setup:
  stage: setup
  script:
    - echo "Setup stage completed."

# Install Stage
install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  only:
    - main

# Build Stage
build:
  stage: build
  script:
    - echo "Build Stage - Running tests and building project"
    - npm run lint
    #    - npm test
    - npm run build
  only:
    - main
  artifacts:
    paths:
      - build/

# Deploy Stage
deploy:
  stage: deploy
  script:
    - docker build -t moms-frontend:latest .
    - docker save moms-frontend:latest | bzip2 | ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'bunzip2 | docker load'
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker stop moms-frontend || true"
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker rm moms-frontend || true"
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "docker run -d -p 80:80 --name moms-frontend moms-frontend:latest"
  environment:
    name: production
  only:
    - main
  before_script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
