image: node:20.12.2

stages:
  - install
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

deploy:
  stage: deploy
  script:
    - npm run build
  only:
    - main